# 异常

java.lang.Throwable 类 Java 语言中所有错误和异常的超类。

Exception: 编译期异常，子类 RuntimeException 运行期异常

Error: 错误

异常处理的五个关键字：try、catch、finally、throw、throws

使用 throw 关键字在指定的方法中抛出指定的异常

格式：

`throw new xxxException("异常产生的元素");`

注意：

1. throw 关键字必须写在方法的内部
2. throw 关键字后面 new 的对象必须是 Exception 对象或者子类对象
3. throw 关键字抛出 RuntimeException 对象或者子类对象，可以不处理，交给 JVM 处理(中断程序，打印出异常对象)
4. throw 关键字抛出编译期异常，必须处理(try...catch 或者 throws)

在实际工作中，首先要对方法的参数进行合法性校验，如果参数不合法，需要抛出异常

`public static <T> T requireNonNull(T obj)`: 查看指定引用对象不是 null。

```java
public class ThrowTest {
  public static void main(String[] args) {
    // 测试方法参数异常
    int[] arr = {1, 2, 3, 4, 5};
    int e = getElement(arr, 4);
    System.out.println(e);

    // 测试非空异常
    getObject(null);

  }
  // 对方法的参数进行合法性校验
  public static int getElement(int[] arr, int idx) {
    // 对 arr 进行非空校验
    if (arr == null) {
      // 空指针异常是运行期异常，可以不处理
      throw new NullPointerException("传递的数组是 null");
    }
    // 判断 idx 是否越界
    if(idx < 0 || idx > arr.length - 1) {
      // 数组索引越界异常是运行期异常，可以不处理
      throw new ArrayIndexOutOfBoundsException("传递的数组索引超出了使用范围");
    }
    return arr[idx];
  }

  // 使用 Objects 的静态方法进行 参数非空校验
  public static void getObject(Object obj) {

//        Objects.requireNonNull(obj);
    Objects.requireNonNull(obj, "传递的对象是 null");

    System.out.println(obj);
  }
}
```

使用 throws 关键字处理异常，把异常抛出给方法的调用者处理

格式：

```java
修饰符 返回值类型 方法名(参数列表) throws AAAException, BBBException, CCCException{
    throw new AAAException(异常产生的原因);
    throw new BBBException(异常产生的原因);
    throw new CCCException(异常产生的原因);
    ...
}
```

注意：

1. throws 关键字必须写在方法声明处
2. throws 关键字后面声明的异常必须是 Exception 或它的子类
3. 方法内部如果抛出了多个异常，throws 后面也必须声明多个异常(直接声明父类即可)
4. 调用了一个声明抛出异常的方法，必须处理(try...catch 或者继续 throws)

```java
public class ThrowsTest {
  // 继续抛出异常，让 JVM 处理
  public static void main(String[] args) throws /*FileNotFoundException,*/ IOException {
    readFile("c:\\a.doc");
  }

  // 声明抛出异常
  // FileNotFoundException extends IOException extends Exception
  // 如果抛出的多个异常存在父子类继承关系，直接声明父类异常即可
  public static void readFile(String fileName) throws /*FileNotFoundException, */ IOException {
    //判断文件路径不是 "c:\\a.txt"
    if (!fileName.equals("c:\\a.txt")) {
      // FileNotFoundException 编译异常，必须处理，使用 throws 继续声明抛出
      throw new FileNotFoundException("文件路径不是c:\\a.txt");
    }
    // 判断是否为 .txt 文件
    if (!fileName.endsWith(".txt")) {
      // 抛出 IO 异常
      throw new IOException("文件的后缀名不正确");
    }
    System.out.println("文件路径正确");
  }
}
```

捕获异常 try-catch

格式：

```java
try {
    可能产生异常的代码
} catch (异常类型 变量名) {
    异常的处理逻辑，一般会把异常记录到一个日志中
} catch (异常类型 变量名) {
    ...
}
```

注意:

1. try 中可以抛出多个异常，可以使用多个 catch 捕获
2. 如果 try 中产生了异常，就会执行 catch，然后继续执行 try-catch 之后的代码

Throwable 类中定义的异常处理方法：

`public String getMessage()`：获取异常的描述信息
`public String toString()`：获取异常的类型和异常描述信息
`public void printStackTrace()`：打印异常的跟踪栈信息并输出到控制台(最全面)

finally 关键字

在 finally 代码块中存放的代码都是一定会被执行

在 try 语句块中打开了一些物理资源(磁盘文件/网络连接/数据库连接等), 可以在 finally 中关闭打开的资源

```java
public class TryCatchTest {
  public static void main(String[] args) {
    // 使用 try-catch 处理异常
    try {
      readFile("c:\\a.doc");
    } catch (IOException e) {
//            System.out.println(e.getMessage()); // 文件的后缀名不正确
//            System.out.println(e.toString()); // java.io.IOException: 文件的后缀名不正确
        e.printStackTrace();
    } finally {
        System.out.println("不管是否有异常都会执行");
    }
    System.out.println("后续代码");
  }

  public static void readFile(String fileName) throws IOException {
    // 判断是否为 .txt 文件
    if (!fileName.endsWith(".txt")) {
        // 抛出 IO 异常
        throw new IOException("文件的后缀名不正确");
    }
  }
}
```

自定义异常类

格式：

```java
public class xxxException extends Exception / RuntimeException {
  空参构造
  带异常信息的构造方法
}
```

```java
public class RegisterException extends Exception {
  // 无参构造
  public RegisterException() {
  }
  // 带异常信息的构造方法
  public RegisterException(String message) {
      super(message);
  }
}

// 模拟注册，如果用户名已存在，则抛出异常
public class RegisterTest {
  static String[] users = {"Leo", "Tom", "Rex", "Van"};
  public static void main(String[] args) /*throws RegisterException*/ {
    Scanner sc = new Scanner(System.in);
    System.out.println("请输入要注册的用户名：");
    String name = sc.next();
    checkName(name);
  }
  public static void checkName(String name) /*throws RegisterException*/ {
      for (String user : users) {
        if (name.equals(user)) {
          // 有相同的用户名，就抛出异常
          try {
            throw new RegisterException("该用户名已注册");
          } catch (RegisterException e) {
            e.printStackTrace();
            return; // 结束方法
          }
        }
      }
      System.out.println("恭喜您，注册成功！");
  }
}
```
